language: c

compiler: gcc

before_script:
    - mkdir build/
    - cd build/
    - cmake ..

script:
    - make -j4
    - make install

after_script:
    - ./test/vector_test
    - ./test/list_test
    - ./test/queue_test
    - ./test/stack_test
    - ./test/ring_buffer_test

notifications:
    email:
        - jianfan.tw@gmail.com
    on_success: change
    on_failure: always
